### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.

### ISSUE THREAD

**Issue by HuiZhang0812** [XLabs-AI/x-flux#109]
I added some modules similar to adapters in `dit`. When I execute the following code,

`dit, optimizer, _, lr_scheduler = accelerator.prepare(
        dit, optimizer, deepcopy(train_dataloader), lr_scheduler)`

 it raises an error:

`Traceback (most recent call last):
  File "/mnt/bn/flux_temp/train_flux_layout_adapter_deepspeed.py", line 413, in <module>
    main()
  File "/mnt/bn/flux_temp/train_flux_layout_adapter_deepspeed.py", line 204, in main
    dit, optimizer, _, lr_scheduler = accelerator.prepare(
                                      ^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/accelerate/accelerator.py", line 1292, in prepare
    result = tuple(
             ^^^^^^
  File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/accelerate/accelerator.py", line 1293, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/accelerate/accelerator.py", line 1169, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/accelerate/accelerator.py", line 1412, in prepare_model
    model = model.to(self.device)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1167, in convert
    raise NotImplementedError(
**NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.**
Traceback (most recent call last):
  File "/root/anaconda3/envs/flux_layout_adapter/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1082, in launch_command
    simple_launcher(args)
  File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/accelerate/commands/launch.py", line 688, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)`

    
I am not using the quantized version. Is there an appropriate solution available?

**Comment by Jeremy-lf** [comment]
> I added some modules similar to adapters in `dit`. When I execute the following code,
> 
> `dit, optimizer, _, lr_scheduler = accelerator.prepare( dit, optimizer, deepcopy(train_dataloader), lr_scheduler)`
> 
> it raises an error:
> 
> `Traceback (most recent call last): File "/mnt/bn/flux_temp/train_flux_layout_adapter_deepspeed.py", line 413, in <module> main() File "/mnt/bn/flux_temp/train_flux_layout_adapter_deepspeed.py", line 204, in main dit, optimizer, _, lr_scheduler = accelerator.prepare( ^^^^^^^^^^^^^^^^^^^^ File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/accelerate/accelerator.py", line 1292, in prepare result = tuple( ^^^^^^ File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/accelerate/accelerator.py", line 1293, in <genexpr> self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/accelerate/accelerator.py", line 1169, in _prepare_one return self.prepare_model(obj, device_placement=device_placement) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/accelerate/accelerator.py", line 1412, in prepare_model model = model.to(self.device) ^^^^^^^^^^^^^^^^^^^^^ File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1174, in to return self._apply(convert) ^^^^^^^^^^^^^^^^^^^^ File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/torch/nn/modules/module.py", line 780, in _apply module._apply(fn) File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/torch/nn/modules/module.py", line 780, in _apply module._apply(fn) File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/torch/nn/modules/module.py", line 780, in _apply module._apply(fn) [Previous line repeated 2 more times] File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/torch/nn/modules/module.py", line 805, in _apply param_applied = fn(param) ^^^^^^^^^ File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1167, in convert raise NotImplementedError( NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device. Traceback (most recent call last): File "/root/anaconda3/envs/flux_layout_adapter/bin/accelerate", line 8, in <module> sys.exit(main()) ^^^^^^ File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main args.func(args) File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1082, in launch_command simple_launcher(args) File "/root/anaconda3/envs/flux_layout_adapter/lib/python3.12/site-packages/accelerate/commands/launch.py", line 688, in simple_launcher raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)`
> 
> I am not using the quantized version. Is there an appropriate solution available?

Have you solved this problem? I also encountered 40G A100
