### ISSUE TITLE
Lora inference error

### ISSUE THREAD

**Issue by ptits** [XLabs-AI/x-flux#13]
Init model
Loading checkpoint
Init AE
Traceback (most recent call last):
  File "/data/ptits/flux/demo_lora_inference.py", line 168, in <module>
    main(args)
  File "/data/ptits/flux/demo_lora_inference.py", line 115, in main
    lora_attn_procs[name].load_state_dict(lora_state_dict)
  File "/data/ptits/flux/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DoubleStreamBlockLoraProcessor:
        size mismatch for qkv_lora1.down.weight: copying a param with shape torch.Size([16, 3072]) from checkpoint, the shape in current model is torch.Size([4, 3072]).
        size mismatch for qkv_lora1.up.weight: copying a param with shape torch.Size([9216, 16]) from checkpoint, the shape in current model is torch.Size([9216, 4]).
        size mismatch for proj_lora1.down.weight: copying a param with shape torch.Size([16, 3072]) from checkpoint, the shape in current model is torch.Size([4, 3072]).
        size mismatch for proj_lora1.up.weight: copying a param with shape torch.Size([3072, 16]) from checkpoint, the shape in current model is torch.Size([3072, 4]).
        size mismatch for qkv_lora2.down.weight: copying a param with shape torch.Size([16, 3072]) from checkpoint, the shape in current model is torch.Size([4, 3072]).
        size mismatch for qkv_lora2.up.weight: copying a param with shape torch.Size([9216, 16]) from checkpoint, the shape in current model is torch.Size([9216, 4]).
        size mismatch for proj_lora2.down.weight: copying a param with shape torch.Size([16, 3072]) from checkpoint, the shape in current model is torch.Size([4, 3072]).
        size mismatch for proj_lora2.up.weight: copying a param with shape torch.Size([3072, 16]) from checkpoint, the shape in current model is torch.Size([3072, 4]).

**Comment by ptits** [comment]
looks like --rank 16 solved the problem

but why it is 4 by default?
