### ISSUE TITLE
DoubleStreamBlockLoraProcessor.forward() takes 6 positional arguments but 8 were given

### ISSUE THREAD

**Issue by ykj467422034** [XLabs-AI/x-flux#135]
hello, when I load lora and inference, a problem is occured
Traceback (most recent call last):                                                                                                                                                                           
  File "/maindata/data/shared/public/kaijia.yan/Flux_img2img_SSRcard/Flux_ipadapter/x-flux/main_test-multi.py", line 143, in <module>                                                                        
    main()                                                                                                                                                                                                   
  File "/maindata/data/shared/public/kaijia.yan/Flux_img2img_SSRcard/Flux_ipadapter/x-flux/main_test-multi.py", line 117, in main                                                                            
    result = xflux_pipeline(                                                                                                                                                                                 
  File "/maindata/data/shared/public/kaijia.yan/Flux_img2img_SSRcard/Flux_ipadapter/x-flux/src/flux/xflux_pipeline.py", line 202, in __call__                                                                
    return self.forward(                                                                                                                                                                                     
  File "/maindata/data/shared/public/kaijia.yan/Flux_img2img_SSRcard/Flux_ipadapter/x-flux/src/flux/xflux_pipeline.py", line 320, in forward                                                                 
    x = denoise(                                                                                                                                                                                             
  File "/maindata/data/shared/public/kaijia.yan/Flux_img2img_SSRcard/Flux_ipadapter/x-flux/src/flux/sampling.py", line 124, in denoise                                                                       
    pred = model(                                                                                                                                                                                            
  File "/opt/conda/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl                                                                                   
    return self._call_impl(*args, **kwargs)                                                                                                                                                                  
  File "/opt/conda/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl                                                                                           
    return forward_call(*args, **kwargs)                                                                                                                                                                     
  File "/maindata/data/shared/public/kaijia.yan/Flux_img2img_SSRcard/Flux_ipadapter/x-flux/src/flux/model.py", line 192, in forward                                                                          
    img, txt = block(                    
File "/opt/conda/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl                                                                                   
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/maindata/data/shared/public/kaijia.yan/Flux_img2img_SSRcard/Flux_ipadapter/x-flux/src/flux/modules/layers.py", line 389, in forward
    return self.processor(self, img, txt, vec, pe, image_proj, ip_scale)
  File "/opt/conda/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: DoubleStreamBlockLoraProcessor.forward() takes 6 positional arguments but 8 were given

**Comment by ykj467422034** [comment]
@lucataco @Anghellia @AndreyML @denmalbas007

**Comment by sunwei317** [comment]
I have the same problem when using BOTH ip-adapter AND Lora, so "DoubleStreamBlockLoraProcessor". However, using either one only works well. I don't know it's bug or a feature that you CANNOT combine ip-adapter with Lora.
