### ISSUE TITLE
Help Needed! How Do I Use the Fine-Tuned ControlNet Outputs in CLI?

### ISSUE THREAD

**Issue by Artemis1111** [XLabs-AI/x-flux#139]
![image](https://github.com/user-attachments/assets/30e492e1-e026-4ffc-b7c3-84cd5bc785c2)

While fine-tuning ControlNet, I ended up with six files as shown in the attached photo. However, I am unsure how to utilize these files.

It seems that `model.safetensors` is the `controlnet.bin` saved in safetensors format, but I don’t know how to use the other files.

I attempted to use `FluxControlNetModel.from_pretrained` from `Diffusers`, but it failed because `config.json` was missing. I also tried using the `config.json` from x-Labs, but encountered an error indicating that certain tensors were missing:

- Error Code
```
Traceback (most recent call last):
  File "/workspace/diffusion_test/FLUX_controlnet.py", line 144, in <module>
    controlnet = FluxControlNetModel.from_pretrained(
  File "/workspace/diffusion_test/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/workspace/diffusion_test/venv/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 848, in from_pretrained
    raise ValueError(
ValueError: Cannot load <class 'diffusers.models.controlnet_flux.FluxControlNetModel'> from /workspace/diffusion_test/model/controlnet/saves_canny/checkpoint-10000 because the following keys are missing: 
 context_embedder.weight, transformer_blocks.0.ff.net.0.proj.weight, time_text_embed.guidance_embedder.linear_2.bias, transformer_blocks.0.attn.to_v.bias, input_hint_block.blocks.1.weight, transformer_blocks.1.attn.to_q.weight, transformer_blocks.1.norm1_context.linear.bias, transformer_blocks.0.attn.add_q_proj.bias, transformer_blocks.0.ff_context.net.2.bias, transformer_blocks.1.attn.to_q.bias, transformer_blocks.1.ff.net.0.proj.bias, transformer_blocks.0.norm1_context.linear.bias, transformer_blocks.0.ff.net.0.proj.bias, controlnet_x_embedder.weight, transformer_blocks.1.attn.add_v_proj.bias, transformer_blocks.0.attn.add_k_proj.bias, transformer_blocks.0.attn.to_add_out.bias, time_text_embed.guidance_embedder.linear_1.weight, transformer_blocks.1.attn.to_out.0.weight, context_embedder.bias, time_text_embed.text_embedder.linear_1.weight, time_text_embed.guidance_embedder.linear_2.weight, x_embedder.bias, transformer_blocks.1.attn.add_k_proj.weight, time_text_embed.timestep_embedder.linear_2.bias, transformer_blocks.0.attn.to_q.weight, input_hint_block.blocks.4.bias, transformer_blocks.0.attn.add_v_proj.bias, input_hint_block.blocks.0.weight, transformer_blocks.0.attn.to_out.0.bias, transformer_blocks.0.norm1_context.linear.weight, transformer_blocks.1.attn.to_k.bias, transformer_blocks.1.attn.to_v.bias, input_hint_block.conv_in.weight, transformer_blocks.0.attn.to_q.bias, input_hint_block.blocks.3.bias, transformer_blocks.1.attn.to_add_out.bias, transformer_blocks.0.ff_context.net.0.proj.weight, transformer_blocks.0.attn.to_k.weight, input_hint_block.conv_out.weight, transformer_blocks.1.attn.norm_added_k.weight, time_text_embed.timestep_embedder.linear_2.weight, input_hint_block.blocks.5.weight, input_hint_block.blocks.2.weight, input_hint_block.blocks.3.weight, transformer_blocks.0.attn.to_out.0.weight, transformer_blocks.0.ff_context.net.0.proj.bias, transformer_blocks.0.ff.net.2.bias, transformer_blocks.1.norm1.linear.bias, transformer_blocks.1.attn.add_q_proj.weight, time_text_embed.text_embedder.linear_1.bias, transformer_blocks.1.ff.net.0.proj.weight, input_hint_block.blocks.2.bias, transformer_blocks.1.ff.net.2.weight, time_text_embed.text_embedder.linear_2.weight, transformer_blocks.0.attn.norm_added_k.weight, transformer_blocks.0.attn.add_k_proj.weight, transformer_blocks.0.attn.add_v_proj.weight, time_text_embed.text_embedder.linear_2.bias, transformer_blocks.1.norm1_context.linear.weight, transformer_blocks.1.attn.norm_q.weight, transformer_blocks.0.attn.add_q_proj.weight, input_hint_block.conv_in.bias, input_hint_block.blocks.5.bias, controlnet_x_embedder.bias, transformer_blocks.1.attn.add_k_proj.bias, transformer_blocks.1.attn.to_k.weight, transformer_blocks.0.ff_context.net.2.weight, transformer_blocks.1.ff.net.2.bias, input_hint_block.conv_out.bias, transformer_blocks.0.ff.net.2.weight, transformer_blocks.0.attn.to_k.bias, transformer_blocks.1.attn.to_out.0.bias, transformer_blocks.0.attn.norm_k.weight, input_hint_block.blocks.0.bias, transformer_blocks.0.norm1.linear.weight, transformer_blocks.1.attn.to_add_out.weight, input_hint_block.blocks.1.bias, transformer_blocks.0.attn.to_add_out.weight, transformer_blocks.1.attn.norm_k.weight, time_text_embed.guidance_embedder.linear_1.bias, transformer_blocks.1.attn.to_v.weight, transformer_blocks.0.attn.to_v.weight, transformer_blocks.1.attn.norm_added_q.weight, transformer_blocks.1.attn.add_q_proj.bias, transformer_blocks.1.ff_context.net.0.proj.bias, transformer_blocks.1.ff_context.net.2.weight, transformer_blocks.0.norm1.linear.bias, time_text_embed.timestep_embedder.linear_1.weight, transformer_blocks.1.attn.add_v_proj.weight, input_hint_block.blocks.4.weight, time_text_embed.timestep_embedder.linear_1.bias, x_embedder.weight, transformer_blocks.1.ff_context.net.2.bias, transformer_blocks.0.attn.norm_q.weight, transformer_blocks.1.norm1.linear.weight, transformer_blocks.0.attn.norm_added_q.weight, transformer_blocks.1.ff_context.net.0.proj.weight. 
 Please make sure to pass low_cpu_mem_usage=False and device_map=None if you want to randomly initialize those weights or else make sure your checkpoint file is correct.
```

Could you provide guidance on how to use these files in **a CLI-based workflow**?
I don’t use GUIs like ComfyUI. 😭

Here are the file sizes from top to bottom:

- 2.8GB
- 2.8GB
- 1.3KB
- 13.9KB
- 988B
- 1000B

What I have tried:

1. Using `FluxControlNetModel.from_pretrained`:

Encountered the error mentioned above.

2. Using `FluxControlNetModel.from_single_file`:

Received an error stating that `FluxControlNetModel` does not support `from_single_file`.

**Comment by Artemis1111** [comment]
https://github.com/huggingface/diffusers/discussions/10258

I found solution.
