### ISSUE TITLE
Low Memory Mode Failing

### ISSUE THREAD

**Issue by ss32** [XLabs-AI/x-flux#20]
## Issue

Running the low memory command results in a failure citing `cannot allocate memory` despite 23GB+ of VRAM available.

```
$ nvidia-smi
```

```
Thu Aug  8 20:14:16 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.06             Driver Version: 535.183.06   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        On  | 00000000:23:00.0  On |                  N/A |
|  0%   52C    P8              50W / 390W |    613MiB / 24576MiB |      9%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

```bash
$ python3 demo_lora_inference.py     --repo_id XLabs-AI/flux-RealismLora     --prompt "A handsome girl in a suit covered with bold tattoos and holding a pistol. Animatrix illustration style, fantasy style, natural photo cinematic" --offload --name flux-dev-fp8
```
```terminal
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
/home/user/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 575, in load_state_dict
    return torch.load(
  File "/home/user/.local/lib/python3.10/site-packages/torch/serialization.py", line 1087, in load
    overall_storage = torch.UntypedStorage.from_file(os.fspath(f), shared, size)
RuntimeError: unable to mmap 44541587809 bytes from file </home/user/.cache/huggingface/hub/models--google--t5-v1_1-xxl/snapshots/3db67ab1af984cf10548a73467f0e5bca2aaaeb2/pytorch_model.bin>: Cannot allocate memory (12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 584, in load_state_dict
    if f.read(7) == "version":
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/deepLearning/x-flux/demo_lora_inference.py", line 173, in <module>
    main(args)
  File "/home/user/deepLearning/x-flux/demo_lora_inference.py", line 98, in main
    model, ae, t5, clip = get_models(
  File "/home/user/deepLearning/x-flux/demo_lora_inference.py", line 23, in get_models
    t5 = load_t5(device, max_length=256 if is_schnell else 512)
  File "/home/user/deepLearning/x-flux/src/flux/util.py", line 234, in load_t5
    return HFEmbedder("google/t5-v1_1-xxl", max_length=max_length, torch_dtype=torch.bfloat16).to(device)
  File "/home/user/deepLearning/x-flux/src/flux/modules/conditioner.py", line 18, in __init__
    self.hf_module: T5EncoderModel = T5EncoderModel.from_pretrained(version, **hf_kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3738, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/user/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 596, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for '/home/user/.cache/huggingface/hub/models--google--t5-v1_1-xxl/snapshots/3db67ab1af984cf10548a73467f0e5bca2aaaeb2/pytorch_model.bin' at '/home/user/.cache/huggingface/hub/models--google--t5-v1_1-xxl/snapshots/3db67ab1af984cf10548a73467f0e5bca2aaaeb2/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```

## Environment:

```
$ pip freeze | grep -E 'accelerate|deepspeed|einops|torch|transformers|huggingface-hub|optimum-quanto|datasets|omegaconf|diffusors'
accelerate==0.30.1
datasets==2.20.0
deepspeed==0.14.4
einops==0.8.0
huggingface-hub==0.24.5
omegaconf==2.3.0
optimum-quanto==0.2.4
transformers==4.43.3
torch==2.4.0
torchaudio==2.4.0+cu124
torchsde==0.2.6
torchvision==0.19.0+cu124
```

**Comment by bghira** [comment]
mmap is actually meaning, you are running out of system memory. this repo isn't optimised for memory use

**Comment by ss32** [comment]
>mmap is actually meaning, you are running out of system memory. 

I realize that but the docs imply that running with a 24GB card works with low memory mode.

**Comment by bghira** [comment]
system memory isn't what they refer to by low memory mode - with deepspeed zero 2 you need quite a lot of system memory. for a 24G card you might need 64-80G system memory.

**Comment by ss32** [comment]
Heard, thanks for clarifying.
