### ISSUE TITLE
SIGKILL when running train_flux_lora_deepspeed.py

### ISSUE THREAD

**Issue by k8tems** [XLabs-AI/x-flux#55]
I'm currently trying to run the script with the following paperspace machine
![image](https://github.com/user-attachments/assets/01bbcf97-12b3-4dab-9f85-d066398199c5)

When doing so, I get this error:
```python
E0818 12:39:45.949000 139699459244032 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: -9) local_rank: 0 (pid: 7522) of binary: /tmp/x-flux/venv/bin/python3.12
Traceback (most recent call last):
  File "/tmp/x-flux/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/tmp/x-flux/venv/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/tmp/x-flux/venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1067, in launch_command
    deepspeed_launcher(args)
  File "/tmp/x-flux/venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 771, in deepspeed_launcher
    distrib_run.run(args)
  File "/tmp/x-flux/venv/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/tmp/x-flux/venv/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/x-flux/venv/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
train_flux_lora_deepspeed.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-18_12:39:45
  host      : n2ocox4owx
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 7522)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 7522
```

**Comment by k8tems** [comment]
The SIGKILL is raised when the script reaches this line

https://github.com/XLabs-AI/x-flux/blob/03639685893d1f1328744ded62b7e51f412d90f0/train_flux_lora_deepspeed.py#L115

`dit` is initially loaded to the cpu in the `get_models` function as bf16
https://github.com/XLabs-AI/x-flux/blob/03639685893d1f1328744ded62b7e51f412d90f0/train_flux_lora_deepspeed.py#L51

Since the `dit` model is 11,907,011,648 parameters and each parameter takes 4 bytes,
I take it `dit.to(torch.float32)` is supposed to consume 47,628,046,592 bytes(i.e. 44.35GB)?

**Comment by k8tems** [comment]
Just to be sure, I modified `torch/nn/modules/module.py` to see the RAM being consumed in real time
![image](https://github.com/user-attachments/assets/71f9ed04-6b82-416f-9494-1e73e38a7a89)

output:
```bash
VRAM 9.469 GB | RAM 4.444 GB / 44.082 GB (11.8%)
total_params_processed=5016967501
...
VRAM 9.469 GB | RAM 42.349 GB / 44.082 GB (97.8%)
total_params_processed=15183082829
VRAM 9.469 GB | RAM 42.458 GB / 44.082 GB (98.0%)
total_params_processed=15211394381
VRAM 9.469 GB | RAM 42.458 GB / 44.082 GB (98.0%)
total_params_processed=15211403597
E0818 12:39:45.949000 139699459244032 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: -9) local_rank: 0 (pid: 7522) of binary: /tmp/x-flux/venv/bin/python3.12
Traceback (most recent call last):
  File "/tmp/x-flux/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/tmp/x-flux/venv/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/tmp/x-flux/venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1067, in launch_command
    deepspeed_launcher(args)
  File "/tmp/x-flux/venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 771, in deepspeed_launcher
    distrib_run.run(args)
  File "/tmp/x-flux/venv/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/tmp/x-flux/venv/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/x-flux/venv/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
train_flux_lora_deepspeed.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-18_12:39:45
  host      : n2ocox4owx
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 7522)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 7522
=====================================================
```
The process crashes after the script processes 15_211_403_597-5_016_967_501=10_194_436_096 dit parameters

**Comment by k8tems** [comment]
If the model weights are initially loaded in bf16, subsequently upcasted to a sparse? float32 and finally passed to `accelerate.prepare`(which probably converts it back to bf16 in cuda), I'm beginning to question if the intermediate float32 conversion is necessary at all.

**Comment by k8tems** [comment]
I'm an idiot. I realize now that this is how mixed precision works.
(Store the weights in fp32 and do the math in half-precision.)
I wonder if there's anything else I can do to reduce the RAM usage.

**Comment by wanglaofei** [comment]
I have the same issue, how to train the flux lora with FLUX with 24G 3090 hardware?

**Comment by k8tems** [comment]
> I have the same issue, how to train the flux lora with FLUX with 24G 3090 hardware?

I gave up on this repo and got it to work with [ai-toolkit](https://github.com/ostris/ai-toolkit)
it works fine out of the box without the weird RAM issue.

**Comment by k8tems** [comment]
Forgot to mention: I was able to bypass the error by commenting out the following line.
https://github.com/XLabs-AI/x-flux/blob/03639685893d1f1328744ded62b7e51f412d90f0/train_flux_lora_deepspeed.py#L115
I have no idea if it breaks it or not.
I decided to give up when I saw that the checkpoint was larger than 50GB
might be an error on my side; maybe I was doing full finetuning instead of lora?
I'm pretty sure I was running the script named train_flux_**lora**_deepspeed.py though...

**Comment by Sainthousand** [comment]
nice, same problem, good solution!
