### ISSUE TITLE
OSError: No such device (os error 19)

### ISSUE THREAD

**Issue by chenzhongzheng** [XLabs-AI/x-flux#60]
python main.py  --prompt "Female furry Pixie with text 'hello world'"  --lora_repo_id XLabs-AI/flux-furry-lora --lora_local_path /data/lora/flux/flux-lora-collection --lora_name furry_lora.safetensors --device cuda:0 --offload --use_lora  --model_type flux-dev-fp8 --width 1024 --height 1024  --timestep_to_start_cfg 1 --num_steps 25 --true_gs 3.5 --guidance 4
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.58s/it]
Init AE
Traceback (most recent call last):
  File "/data/image/x-flux/main.py", line 136, in <module>
    main(args)
  File "/data/image/x-flux/main.py", line 109, in main
    xflux_pipeline = XFluxPipeline(args.model_type, args.device, args.offload, args.seed)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/image/x-flux/src/flux/xflux_pipeline.py", line 22, in __init__
    self.ae = load_ae(model_type, device="cpu" if offload else self.device)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/image/x-flux/src/flux/util.py", line 337, in load_ae
    sd = load_sft(ckpt_path, device=str(device))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/xflux/lib/python3.11/site-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: No such device (os error 19)

NVIDIA TITAN RTX
CUDA Version: 12.4

**Comment by arrowonstr** [comment]
I think it happens when filename is a dictory rather than a file name
Did u export FLUX_DEV and AE? 
If do, make sure export FLUX='path/flux1-dev.saftertensors' rather than 'path/'

**Comment by chenzhongzheng** [comment]
嗯嗯，多谢！已解决。

**Comment by fenghe12** [comment]
这个报错有点太让人迷惑了
