### ISSUE TITLE
RuntimeError: mat1 and mat2 must have the same dtype, but got Half and BFloat16

### ISSUE THREAD

**Issue by chenzhongzheng** [XLabs-AI/x-flux#63]
python3 main.py --prompt "A cute corgi lives in a house made out of sushi, anime" --lora_repo_id XLabs-AI/flux-lora-collection --lora_local_path /data/aqzx/xinference/lora/flux/flux-lora-collection/anime_lora.safetensors --device cuda --offload --use_lora --model_type flux-schnell --width 1024 --height 1024
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.67s/it]
Init AE
Init model
Loading checkpoint
load lora: /data/xinference/lora/flux/flux-lora-collection/anime_lora.safetensors XLabs-AI/flux-lora-collection None
Loading .safetensors checkpoint...
Traceback (most recent call last):
  File "/data/image/x-flux/main.py", line 136, in <module>
    main(args)
  File "/data/image/x-flux/main.py", line 118, in main
    result = xflux_pipeline(prompt=args.prompt,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/image/x-flux/src/flux/xflux_pipeline.py", line 96, in __call__
    return self.forward(prompt, width, height, guidance, num_steps, controlnet_image,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/image/x-flux/src/flux/xflux_pipeline.py", line 132, in forward
    x = denoise(self.model, **inp_cond, timesteps=timesteps, guidance=guidance,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/image/x-flux/src/flux/sampling.py", line 119, in denoise
    pred = model(
           ^^^^^^
  File "/data/anaconda3/envs/xflux/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/xflux/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/image/x-flux/src/flux/model.py", line 152, in forward
    img = self.img_in(img)
          ^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/xflux/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/xflux/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/xflux/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 must have the same dtype, but got Half and BFloat16

NVIDIA TITAN RTX
CUDA Version: 12.4

My GPU doesn't support bf16 computation. I've modified the code to use float16 instead of bfloat16, but I'm getting this error with model_type flux-dev and flux-schnell, while flux-dev-f8 works fine.

**Comment by sharad-anyway** [comment]
Has anybody been able to resolve this? I am having the same issue.


_______________________________________
UPDATE
______________________________________

Using torch.autocast() helped me fix this.

```
with torch.autocast("cuda", dtype=torch.bfloat16):
    generated_image = pipe(
        prompt = "",
        image = input_image,
        guidance_scale = 3.5,
        ip_adapter_image_embeds = ip_adapter_image_embeds,
        num_inference_steps = 50,
        num_images_per_prompt = 1,
        
    ).images[0]
```
